export const USER_STATES = [
  "NEW_USER",
  "ONBOARDING_GOAL",
  "ONBOARDING_STYLE",
  "ONBOARDING_FREQUENCY",
  "ONBOARDING_REMINDER_DAY",
  "ONBOARDING_REMINDER_TIME",
  "ONBOARDING_INTAKE",
  "READY",
  "WAITING_FOR_WEEKLY_INPUT",
  "TRANSCRIBING_AUDIO",
  "GENERATING_QUESTIONS",
  "WAITING_FOR_ANSWERS",
  "GENERATING_CHAPTER",
  "REVIEWING_CHAPTER",
  "CHAPTER_SAVED"
] as const;

export type UserStateValue = (typeof USER_STATES)[number];

const GLOBAL_INTERRUPTS = new Set<UserStateValue>(["READY", "WAITING_FOR_WEEKLY_INPUT"]);

const TRANSITIONS: Record<UserStateValue, UserStateValue[]> = {
  NEW_USER: ["ONBOARDING_GOAL", "ONBOARDING_REMINDER_TIME", "ONBOARDING_INTAKE", "READY"],
  ONBOARDING_GOAL: ["ONBOARDING_STYLE", "READY"],
  ONBOARDING_STYLE: ["ONBOARDING_FREQUENCY", "READY"],
  ONBOARDING_FREQUENCY: ["ONBOARDING_REMINDER_DAY", "ONBOARDING_REMINDER_TIME", "READY"],
  ONBOARDING_REMINDER_DAY: ["ONBOARDING_REMINDER_TIME", "READY"],
  ONBOARDING_REMINDER_TIME: ["ONBOARDING_INTAKE", "READY", "WAITING_FOR_WEEKLY_INPUT"],
  ONBOARDING_INTAKE: ["GENERATING_CHAPTER", "READY", "WAITING_FOR_WEEKLY_INPUT"],
  READY: ["WAITING_FOR_WEEKLY_INPUT", "ONBOARDING_GOAL", "ONBOARDING_STYLE", "ONBOARDING_FREQUENCY", "ONBOARDING_INTAKE"],
  WAITING_FOR_WEEKLY_INPUT: ["TRANSCRIBING_AUDIO", "GENERATING_QUESTIONS", "GENERATING_CHAPTER", "READY"],
  TRANSCRIBING_AUDIO: ["GENERATING_QUESTIONS", "GENERATING_CHAPTER", "WAITING_FOR_WEEKLY_INPUT", "READY"],
  GENERATING_QUESTIONS: ["WAITING_FOR_ANSWERS", "GENERATING_CHAPTER", "READY"],
  WAITING_FOR_ANSWERS: ["GENERATING_CHAPTER", "READY", "WAITING_FOR_WEEKLY_INPUT"],
  GENERATING_CHAPTER: ["REVIEWING_CHAPTER", "READY"],
  REVIEWING_CHAPTER: ["CHAPTER_SAVED", "GENERATING_CHAPTER", "READY"],
  CHAPTER_SAVED: ["READY", "WAITING_FOR_WEEKLY_INPUT"]
};

export function canTransition(from: UserStateValue, to: UserStateValue): boolean {
  return from === to || TRANSITIONS[from]?.includes(to) || GLOBAL_INTERRUPTS.has(to);
}

export function assertTransition(from: UserStateValue, to: UserStateValue): void {
  if (!canTransition(from, to)) {
    throw new Error(`Invalid user state transition: ${from} -> ${to}`);
  }
}
